include ../../setup_guard.mk

TOPLEVEL=posit_adder
MODULE=test_posit_adder

# redefine VERILOG_SOURCES to reduce necessary compilation
VERILOG_SOURCES=${RTL_TOP}/common.sv ${RTL_TOP}/posit_adder.sv

include $(COCOTB_TOP)/template.mk
