include ../../setup_guard.mk

TOPLEVEL=find_first_n_ones
MODULE=test_ffno

# redefine VERILOG_SOURCES to reduce necessary compilation
VERILOG_SOURCES=${RTL_TOP}/common.sv ${RTL_TOP}/find_first_n_ones.sv

include ${COCOTB_TOP}/template.mk
