include ../../setup_guard.mk

TOPLEVEL=format_decoder
MODULE=test_decoder

# redefine VERILOG_SOURCES to reduce necessary compilation
VERILOG_SOURCES=${RTL_TOP}/common.sv ${RTL_TOP}/format_decoder.sv

include ${COCOTB_TOP}/template.mk
