include ../../setup_guard.mk

TOPLEVEL=dff
MODULE=test_dff

# redefine VERILOG_SOURCES to reduce necessary compilation
VERILOG_SOURCES=${RTL_TOP}/common.sv ${RTL_TOP}/dff.sv

include ${COCOTB_TOP}/template.mk
