include ../../setup_guard.mk

TOPLEVEL=find_first_one
MODULE=test_ffo

# redefine VERILOG_SOURCES to reduce necessary compilation
VERILOG_SOURCES=${RTL_TOP}/common.sv ${RTL_TOP}/find_first_one.sv

include ${COCOTB_TOP}/template.mk
