include ../../setup_guard.mk

TOPLEVEL=count_lead_zero
MODULE=test_clz

# redefine VERILOG_SOURCES to reduce necessary compilation
VERILOG_SOURCES=${RTL_TOP}/common.sv ${RTL_TOP}/count_lead_zero.sv

include ${COCOTB_TOP}/template.mk
