[project]
name = "fric"
version = "0.0.1"
authors = [
    {name = "Luke Andrews"},
    {name = "Henry Franks"},
    {name = "Harry Rodgers"},
]
dependencies = [
  'cocotb == 1.8.0',
]
[tool.setuptools.packages.find]
where = ["src"]
namespaces = false
