name: Verification

on: [push]

jobs:
  verif_cocotb:
    runs-on: macos-12

    steps:
    - uses: actions/checkout@v2

    - uses: actions/cache@v3
      with:
        path: ~/.cache/verif/cocotb
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        brew install verilator@5.012

    - name: Verify with cocotb & verilator
      working-directory: ./hdl/verif/cocotb
      run: |
        source setup.sh
        pytest