name: Verification

on: [push]

jobs:
  verif_cocotb:
    runs-on: macos-13

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        cache: 'pip'

    - name: Install dependencies
      run: |
        pip3 install -r requirements.txt
        brew install verilator

    - name: Verify with cocotb & verilator
      working-directory: ./hdl/verif/cocotb
      run: |
        source setup.sh
        pytest

  verif_msim:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
    