include ../../setup_guard.mk

TOPLEVEL=count_lead_one
MODULE=test_clo

# redefine VERILOG_SOURCES to reduce necessary compilation
VERILOG_SOURCES=${RTL_TOP}/common.sv ${RTL_TOP}/count_lead_one.sv

include ${COCOTB_TOP}/template.mk
